### ISSUE TITLE
Boat stop icon

### ISSUE THREAD

**Issue by overflorian** [Jungle-Bus/bus_osmtracker_layout#1]
Here's the new icon for the boat stop that we should implent.
Thanks

[Pictos Bateau.zip](https://github.com/Jungle-Bus/osmtracker-layouts/files/3169198/Pictos.Bateau.zip)

**Comment by nlehuby** [comment]
![](https://github.com/Jungle-Bus/osmtracker-layouts/raw/master/layouts/ferry_route/layout.png)
